force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Is_Correct__c.field-meta.xml
<CustomField>
    <fullName>Is_Correct__c</fullName>
    <label>Is Correct</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Question_Answer__c/Unit_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>Unit Question Answer</label>
    <nameField>
        <displayFormat>UQA-{0000}</displayFormat>
        <label>Unit Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units Questions Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Question_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Units Questions Answers</relationshipLabel>
    <relationshipName>Units_Questions_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Question_Answer__c/fields/User_Unit__c.field-meta.xml
<CustomField>
    <fullName>User_Unit__c</fullName>
    <label>User Unit</label>
    <referenceTo>User_Unit__c</referenceTo>
    <relationshipLabel>Units Questions Answers</relationshipLabel>
    <relationshipName>Units_Questions_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Unit__c/User_Unit__c.object-meta.xml
<CustomObject>
    <label>User Unit</label>
    <nameField>
        <displayFormat>UUN-{0000}</displayFormat>
        <label>User Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UserUnitResponseHelper.cls
public with sharing class UserUnitResponseHelper {
  public static void evaluateResponse(
    Boolean isBeforeUpdate,
    List<User_Unit__c> userUnits,
    Map<Id, User_Unit__c> oldUserUnitMap
  ) {
    if (isBeforeUpdate) {
      List<User_Unit__c> draftToAnswered = new List<User_Unit__c>();
      for (User_Unit__c userUnit : userUnits) {
        if (isDraftToAnswered(userUnit, oldUserUnitMap)) {
          draftToAnswered.add(userUnit);
        }
      }

      if (draftToAnswered.size() > 0) {
        List<Unit_Question_Answer__c> answersResult = [
          SELECT Answer__r.Is_Correct__c, User_Unit__c
          FROM Unit_Question_Answer__c
          WHERE User_Unit__c IN :draftToAnswered
        ];

        for (User_Unit__c toUpdate : draftToAnswered) {
          if (isSuccess(toUpdate, answersResult)) {
            toUpdate.Status__c = 'Success';
          } else {
            toUpdate.Status__c = 'Fail';
          }
        }

      }

    }
  }

  public static Boolean isDraftToAnswered(User_Unit__c userUnit, Map<Id, User_Unit__c> oldMap) {
    return userUnit.Status__c == 'Answered' && oldMap.get(userUnit.Id).Status__c == 'Draft';
  }

  public static Boolean isSuccess(User_Unit__c userUnit, List<Unit_Question_Answer__c> answersResult) {
    for (Unit_Question_Answer__c result : answersResult) {
      if (result.User_Unit__c == userUnit.Id && result.Answer__r.Is_Correct__c == 'No') {
        return false;
      }
    }

    return true;
  }

  public static Map<Id, Boolean> isSuccessMap(List<Unit_Question_Answer__c> answersResult) {
    Map<Id, Boolean> successMap = new Map<Id, Boolean>();

    for (Unit_Question_Answer__c result : answersResult) {
      if (successMap.get(result.User_Unit__c) == null || successMap.get(result.User_Unit__c)) {
        Boolean isCorrect = result.Answer__r.Is_Correct__c == 'Yes';
        successMap.put(result.User_Unit__c, isCorrect);
      }
    }

    return successMap;
  }
}