force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Question_Answer__c/Unit_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>Unit Question Answer</label>
    <nameField>
        <displayFormat>UQA-{0000}</displayFormat>
        <label>Unit Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units Questions Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Question_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Units Questions Answers</relationshipLabel>
    <relationshipName>Units_Questions_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Question_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Units Questions Answers</relationshipLabel>
    <relationshipName>Units_Questions_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Question_Answer__c/fields/User_Unit__c.field-meta.xml
<CustomField>
    <fullName>User_Unit__c</fullName>
    <label>User Unit</label>
    <referenceTo>User_Unit__c</referenceTo>
    <relationshipLabel>Units Questions Answers</relationshipLabel>
    <relationshipName>Units_Questions_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Module__c/User_Module__c.object-meta.xml
<CustomObject>
    <label>User Module</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>User_Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipName>User_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Module__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Module__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Unit__c/User_Unit__c.object-meta.xml
<CustomObject>
    <label>User Unit</label>
    <nameField>
        <displayFormat>UUN-{0000}</displayFormat>
        <label>User Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>User Units</relationshipLabel>
    <relationshipName>User_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Unit__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Unit__c/fields/User_Module__c.field-meta.xml
<CustomField>
    <fullName>User_Module__c</fullName>
    <label>User_Module</label>
    <referenceTo>User_Module__c</referenceTo>
    <relationshipLabel>User Units</relationshipLabel>
    <relationshipName>User_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UnitService.cls
public with sharing class UnitService {
  public static void unitResponseProcess(Id unitId, String questionAnswer) {
    // grab the logged userId
    Id currentUserId = UserInfo.getUserId();

    Map<Id, Id> questionAnswerMap = (Map<Id, Id>) JSON.deserializeStrict(
      questionAnswer,
      Map<Id, Id>.class
    );

    User_Unit__c unitModuleResponse = new User_Unit__c(
      Status__c = 'Draft',
      Unit__c = unitId,
      User__c = currentUserId
    );

    // ToDo: check if the user did make an attempt to answer this unit
    //       if true -> asign the User_Module Id to the unitModuleResponse
    //       if false -> create a new User_Module for currentUser with Status inProgress
    //                   and asign the new User_Module  Id to the unitModuleResponse
    User_Module__c currentModule;

    Unit__c unit = [SELECT Id, Module__c FROM Unit__c WHERE Id = :unitId];

    List<User_Module__c> moduleList = [
      SELECT Id
      FROM User_Module__c
      WHERE Module__c = :unit.Module__c AND User__c = :currentUserId
    ];

    if (moduleList.size() > 0) {
      currentModule = moduleList.get(0);
    } else {
      currentModule = new User_Module__c(
        Module__c = unit.Module__c,
        User__c = currentUserId,
        Status__c = 'In Progress'
      );
      insert currentModule;
    }

    unitModuleResponse.User_Module__c = currentModule.Id;

    insert unitModuleResponse;

    // create the option(Unit_Question_Answer__c sObjects) for the
    // curent attempt to complete the Unit
    List<Unit_Question_Answer__c> questionAnswerList = new List<Unit_Question_Answer__c>();
    for (String questionId : questionAnswerMap.keySet()) {
      String answerId = questionAnswerMap.get(questionId);
      Unit_Question_Answer__c option = new Unit_Question_Answer__c(
        User_Unit__c = unitModuleResponse.Id,
        Question__c = questionId,
        Answer__c = answerId
      );
      questionAnswerList.add(option);
    }

    insert questionAnswerList;

    unitModuleResponse.Status__c = 'Answered';
    update unitModuleResponse;
  }
}