force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <summarizedField>Unit__c.Duration__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business User</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Marketer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Lightning</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>App Lifecycle</fullName>
            </value>
            <value>
                <fullName>App Logic</fullName>
            </value>
            <value>
                <fullName>Database</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>Total Points</label>
    <summarizedField>Unit__c.Points__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Count__c.field-meta.xml
<CustomField>
    <fullName>Unit_Count__c</fullName>
    <label>Unit Count</label>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trail__c/Trail__c.object-meta.xml
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/Trail_Module__c.object-meta.xml
<CustomObject>
    <label>Trail_Module</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Trail Module</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trail_Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Trail_Modules</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipLabel>Trail_Modules</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Module__c/User_Module__c.object-meta.xml
<CustomObject>
    <label>User Module</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>User_Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipName>User_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Module__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Module__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrailWrapper.cls
public with sharing class TrailWrapper {
  private Id userId;
  private Id trailId;
  //Registro de Trail solicitado
  public Trail__c trail;
  //Porcentaje de progreso del Alumno en el Trail
  public Integer progressTrail;

  private Trail__c trailWithModules;

  //Módulos con Unidades relacionadas
  private List<Module__c> modules = new List<Module__c>();

  private Set<Id> moduleIds = new Set<Id>();

  //Ids de módulos relacionados al Trail actual en los que el Alumno ya aprobó
  private Set<Id> passedModuleIds = new Set<Id>();
  //Ids de Unidades relacionadas a módulos del Trail actual que el Alumno ya aprobó
  private Set<Id> passedUnitIds = new Set<Id>();

  public TrailWrapper(Id trailId, Id userId) {
    this.userId = userId;
    this.trailId = trailId;
    initializeProperties(trailId);
  }

  private void initializeProperties(Id trailId) {
    this.trailWithModules = [
      SELECT
        Name,
        Description__c,
        Total_Points__c,
        Duration__c,
        (
          SELECT
            Module__c,
            Module__r.Name,
            Module__r.Description__c,
            Module__r.Role__c,
            Module__r.Skills__c,
            Module__r.Total_Points__c,
            Module__r.Unit_Count__c
          FROM Trail_Modules__r
        )
      FROM Trail__c
      WHERE Id = :trailId
    ];

    this.trail = this.parseTrail(this.trailWithModules);
    this.fillModules(this.trailWithModules.Trail_Modules__r);

    this.fillPassedModules();
  }

  private void fillPassedModules() {
    List<User_Module__c> userModulesWithUserUnits = [
      SELECT Id, Module__c, Status__c
      FROM User_Module__c
      WHERE User__c = :this.userId AND Module__c IN :moduleIds
    ];

    for (User_Module__c userModule : userModulesWithUserUnits) {
      if (userModule.Status__c == 'Completed') {
        this.passedModuleIds.add(userModule.Module__c);
      }
    }
  }

  private void fillTrails() {
  }

  private void fillModules(List<Trail_Module__c> trailModules) {
    for (Trail_Module__c trailModule : trailModules) {
      this.modules.add(this.parseModule(trailModule));
      this.moduleIds.add(trailModule.Module__c);
    }
  }

  private Module__c parseModule(Trail_Module__c toParse) {
    return new Module__c(
      Id = toParse.Module__c,
      Name = toParse.Module__r.Name,
      Description__c = toParse.Module__r.Description__c,
      Role__c = toParse.Module__r.Role__c,
      Skills__c = toParse.Module__r.Skills__c
    );
  }

  private Trail__c parseTrail(Trail__c toParse) {
    return new Trail__c(
      Id = toParse.Id,
      Name = toParse.Name,
      Description__c = toParse.Description__c,
      Total_Points__c = toParse.Total_Points__c,
      Duration__c = toParse.Duration__c
    );
  }

  public List<Module__c> getModules() {
    return this.modules;
  }
  public Set<Id> getPassedModuleIds() {
    return this.passedModuleIds;
  }
  public Set<Id> getPassedUnitIds() {
    return this.passedUnitIds;
  }
}